spring.application.name=eating

# BD
spring.datasource.url=jdbc:postgresql://localhost:5432/eating
spring.datasource.username=admeating
spring.datasource.password=vasechko
spring.datasource.driver-class-name=org.postgresql.Driver

# ???????? Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flyway=DEBUG
logging.level.org.hibernate=DEBUG

#JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
