CREATE TABLE products (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
quantity INTEGER NOT NULL,
price NUMERIC(18, 2),
location VARCHAR(20) NOT NULL CHECK (location IN ('KITCHEN','WAREHOUSE')) );


CREATE TABLE dishes (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL );


CREATE TABLE dish_ingredients (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
dish_id BIGINT NOT NULL,
product_id BIGINT NOT NULL,
quantity_required INTEGER NOT NULL,
CONSTRAINT fk_dish FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE CASCADE,
CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(id) );


CREATE TABLE procurement_items (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
product_name VARCHAR(255) NOT NULL,
missing_quantity INTEGER NOT NULL,
related_dish_id BIGINT,
created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
CONSTRAINT fk_related_dish FOREIGN KEY (related_dish_id) REFERENCES dishes(id) );